### ISSUE TITLE
Scrolly text sliding under headers on neighborhood map

### ISSUE THREAD

**Issue by rhandleymcc** [mcclatchy/security-for-sale#12]
across all platforms

**Comment by rhandleymcc** [comment]
https://user-images.githubusercontent.com/101584475/165869815-35ec9c6a-909e-49a4-bbe0-2e179c318af3.MP4

**Comment by dmnewcomb** [comment]
I was able to fix this by tying the map opacity to the video opacity. When the video is visible, the map is invisible (instead of how it was earlier where the video was laying on top of the map invisible, then temporarily became visible). Then the map and video can exist at the same `z-index` level, which allows the other layering of legends and text boxes to work as expected.
